[build]
  command = "npm run build"
  publish = "build"

[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = "frontend/sveltekit"
